server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/erp
    username: postgres
    password: 111

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true


  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  access:
    key: 7#70OZn0#Dsaodi98BK8C1%T&hBnrzgqK28o
    expiration-time: 7200000000
  refresh:
    key: 7787dsa8dp7#%70OZ()BK8C1%Taskldjksal***
    expiration-time: 604800000

logging:
  file:
    name: amcis.log

app:
  admin:
    email: "+998991234567"
    password: Root_321
  upload:
    folder: D:\TestB20\
